from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Any, Dict, List, Optional, Sequence, Tuple, Union

import torch

if TYPE_CHECKING:
    from .context import CKKSInferenceContext


class EncryptedTensor:
    shape: Tuple[int, ...]
    size: int
    ndim: int
    depth: int
    level: int
    scale: float
    metadata: Dict[str, Any]
    context: CKKSInferenceContext

    def __init__(self, cipher: Any, shape: Tuple[int, ...], context: Any, depth: int = 0) -> None: ...

    def add(self, other: Union[EncryptedTensor, torch.Tensor, float, int, List[float]]) -> EncryptedTensor: ...
    def sub(self, other: Union[EncryptedTensor, torch.Tensor, float, int, List[float]]) -> EncryptedTensor: ...
    def mul(self, other: Union[EncryptedTensor, torch.Tensor, float, int, List[float]]) -> EncryptedTensor: ...
    def neg(self) -> EncryptedTensor: ...
    def div(self, divisor: float) -> EncryptedTensor: ...
    def square(self) -> EncryptedTensor: ...

    def rescale(self) -> EncryptedTensor: ...
    def rotate(self, steps: int) -> EncryptedTensor: ...
    def sum_slots(self) -> EncryptedTensor: ...
    def sum_and_broadcast(self, n: int) -> EncryptedTensor: ...
    def bootstrap(self) -> EncryptedTensor: ...
    def maybe_bootstrap(self, context: Optional[CKKSInferenceContext] = None) -> EncryptedTensor: ...
    def conjugate(self) -> EncryptedTensor: ...
    def mul_by_i(self) -> EncryptedTensor: ...
    def extract_real(self) -> EncryptedTensor: ...
    def extract_imag(self) -> EncryptedTensor: ...

    def poly_eval(self, coeffs: Sequence[float]) -> EncryptedTensor: ...
    def inv_sqrt(self, domain: Optional[Tuple[float, float]] = None, shallow: bool = False) -> EncryptedTensor: ...
    def sqrt(self, domain: Tuple[float, float] = ...) -> EncryptedTensor: ...

    def matmul(
        self,
        weight: torch.Tensor,
        bias: Optional[torch.Tensor] = None,
        *,
        use_bsgs: Optional[bool] = None,
        weight_list: Optional[list] = None,
        bias_list: Optional[list] = None,
        weight_hash: int = 0,
        diag_nonzero: Optional[list] = None,
    ) -> EncryptedTensor: ...
    def matmul_packed(
        self,
        weight: torch.Tensor,
        bias: Optional[torch.Tensor] = None,
        *,
        weight_list: Optional[list] = None,
        bias_list: Optional[list] = None,
        weight_hash: int = 0,
        diag_nonzero: Optional[list] = None,
    ) -> EncryptedTensor: ...

    def packed_self_attention_power(
        self,
        key: EncryptedTensor,
        value: EncryptedTensor,
        *,
        batch_size: int,
        seq_len: int,
        embed_dim: int,
        scale: float,
        shift: float,
        reciprocal_coeffs: Sequence[float],
        renorm_reciprocal_coeffs: Sequence[float],
    ) -> EncryptedTensor: ...

    def view(self, *shape: int) -> EncryptedTensor: ...
    def reshape(self, shape: Union[int, Tuple[int, ...]]) -> EncryptedTensor: ...
    def flatten(self) -> EncryptedTensor: ...

    def decrypt(self, shape: Optional[Sequence[int]] = None) -> torch.Tensor: ...
    def __add__(self, other: Union[EncryptedTensor, torch.Tensor, float, int, List[float]]) -> EncryptedTensor: ...
    def __radd__(self, other: Union[EncryptedTensor, torch.Tensor, float, int, List[float]]) -> EncryptedTensor: ...
    def __sub__(self, other: Union[EncryptedTensor, torch.Tensor, float, int, List[float]]) -> EncryptedTensor: ...
    def __rsub__(self, other: Union[EncryptedTensor, torch.Tensor, float, int, List[float]]) -> EncryptedTensor: ...
    def __mul__(self, other: Union[EncryptedTensor, torch.Tensor, float, int, List[float]]) -> EncryptedTensor: ...
    def __rmul__(self, other: Union[EncryptedTensor, torch.Tensor, float, int, List[float]]) -> EncryptedTensor: ...
    def __neg__(self) -> EncryptedTensor: ...

    def save(self, path: Union[str, Path]) -> None: ...

    @classmethod
    def load(cls, path: Union[str, Path], context: CKKSInferenceContext) -> EncryptedTensor: ...
